version: '3.8'

services:
  backend:
    build: ./Docker-server-deployement
    ports:
      - "8000:8000"
    volumes:
      - ./Docker-server-deployement/Server:/app/Server
    restart: unless-stopped

  frontend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - backend
    restart: unless-stopped